name: flow
channels:
  - pytorch
  - defaults
dependencies:
  - python ==3.7.3
  - pip:
      - scipy==1.1.0
      - lxml==4.4.1
      - six==1.11.0
      - path==16.6.0
      - path-py==12.5.0
      - python-dateutil==2.7.3
      - pip==23.1.2
      - tensorboard==1.15.0
      - tensorboardx==2.6
      - tensorflow==1.15.2
      - tensorflow-estimator==1.15.1
      - setuptools==41.0.0
      - plotly==2.4.0
      - gym==0.14.0
      - pyprind==2.11.2
      - nose2==0.8.0
      - cached-property==1.5.2
      - joblib==0.10.3
      - dill==0.3.6
      - lz4==4.3.2
      - ray==0.8.0
      - setproctitle==1.3.2
      - psutil==5.9.5
      - opencv-python==4.7.0.72
      - boto3==1.10.45
      - redis==3.3.11
      - nngeometry==0.2.1     
      - numpy==1.18.4
      - pandas==0.24.2
      - torch==1.7.0
      - tqdm==4.65.0

